spring:
    jpa:
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: false
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:test
        username: root
        password:
