#!/usr/bin/env bash

docker stop tasks
docker rm tasks
docker rmi tasks

rm -rf /root/tasks/project
git clone -b master /root/tasks/git /root/tasks/project

cd /root/tasks/project

bash -x gradlew buildDocker --no-daemon --stacktrace -Dprod -Pprofile=prod -x test

docker logs -f tasks